### ISSUE TITLE
InvariantViolationError when verifying a network

### ISSUE THREAD

**Issue by XuankangLin** [guykatzz/ReluplexCav2017#7]
Hi,

I have encountered this **InvariantViolationError** when verifying a neural network. This has happened many times when I perturbed my network weights more manually, but not "canonically trained" using existing ML frameworks. Any idea why this is the case and how to fix that? Does Reluplex impose any internal requirements on the network weights?

I have extracted the error test case (main.cpp + error.nnet + Makefile) that aborts in such setting. Unzip the directory to under /check_properties/ and compile and run directly, then it should replay what I describe above.

Thanks.
[sentiment_prop.zip](https://github.com/guykatzz/ReluplexCav2017/files/2394060/sentiment_prop.zip)

**Comment by guykatzz** [comment]
Hi Andriy,
I committed a fix on the "pp_fix" branch. Could you please check that it solves the problem for you? If so, I'll merge it to the master branch.

Thanks,
Guy

**Comment by XuankangLin** [comment]
Yes, that would eliminate the issue I was having. Thanks.
